version: '3.7'
services:

  insertar-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deployment
    image: imagen-insertar-registros
    container_name: insertar-app
    restart: always
    ports:
      - 9081:9081
    volumes:
      - mysqldata:/app/logs
    depends_on:
      - mysqldb
    networks:
      - network

  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tramadb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - network

volumes:
  mysqldata:

networks:
  network:
    driver: bridge
    name: network_demo_tdd