version: '3.7'
services:

  enviar-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deployment
    image: imagen-enviar-registros
    container_name: enviar-app
    restart: always
    ports:
      - 9080:9080
    volumes:
      - h2data:/app/logs
    networks:
      - network

volumes:
  h2data:

networks:
  network:
    driver: bridge
    name: network_demo_tdd