version: '3.7'
services:

  enviar-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deployment
    image: imagen-enviar-registros
    container_name: enviar-app
    restart: always
    ports:
      - 9080:9080
#    depends_on:
#      - mysqldb
    networks:
      - network

#  mysqldb:
#    image: mysql:5.7
#    container_name: mysqldb
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: tramadb
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:
#      - 3306:3306
#    networks:
#      - network

networks:
  network:
    driver: bridge
    name: network_demo_tdd